import type { AdditionalRuleDefinition, AdditionalRuleId } from '../types/rules';

export const ADDITIONAL_RULES: Record<AdditionalRuleId, AdditionalRuleDefinition> = {
  // ============================================================
  // 既存ルール (11個)
  // ============================================================
  ten_discard: {
    id: 'ten_discard',
    nameJa: '10捨て',
    descriptionJa: '10のカードを出したら、出した枚数分好きなカードを手札から捨てることができる。',
    triggerRank: 10,
    triggerCount: 1,
    type: 'on_play',
  },
  twelve_bomber: {
    id: 'twelve_bomber',
    nameJa: '12ボンバー',
    descriptionJa: 'Q(12)のカードを出したら、出した枚数分好きな数字を宣言し、その数字のカードを持っている人は全員捨てる。',
    triggerRank: 12,
    triggerCount: 1,
    type: 'on_play',
  },
  five_skip: {
    id: 'five_skip',
    nameJa: '5スキップ',
    descriptionJa: '5のカードを出したら、出した枚数分次の人の順番を飛ばす。',
    triggerRank: 5,
    triggerCount: 1,
    type: 'on_play',
  },
  seven_pass: {
    id: 'seven_pass',
    nameJa: '7渡し',
    descriptionJa: '7のカードを出したら、出した枚数分次の番の人にカードを渡す。',
    triggerRank: 7,
    triggerCount: 1,
    type: 'on_play',
  },
  four_revive: {
    id: 'four_revive',
    nameJa: '4者蘇生',
    descriptionJa: '4のカードを出したら、出した枚数分、既に捨てられたカードの中からランダムで手札に加える。',
    triggerRank: 4,
    triggerCount: 1,
    type: 'on_play',
  },
  capital_fall: {
    id: 'capital_fall',
    nameJa: '都落ち',
    descriptionJa: '前のゲームの大富豪が1位であがれなかった場合、強制的に大貧民になる。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  even_odd_alternate: {
    id: 'even_odd_alternate',
    nameJa: '偶奇交互制',
    descriptionJa: '偶数と奇数を交互に出さなくてはならない。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  suit_ban: {
    id: 'suit_ban',
    nameJa: '同種禁止制',
    descriptionJa: '場が流れた後、最初に出すカードは前の最後のマークと同じマークを出せない。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  sandstorm: {
    id: 'sandstorm',
    nameJa: '砂嵐',
    descriptionJa: '3のカードを3枚出すと、いつでも場を流せる。',
    triggerRank: 3,
    triggerCount: 3,
    type: 'field_clear',
  },
  ambulance: {
    id: 'ambulance',
    nameJa: '救急車',
    descriptionJa: '9のカードを2枚出すと、いつでも場を流せる。',
    triggerRank: 9,
    triggerCount: 2,
    type: 'field_clear',
  },
  king_reverse: {
    id: 'king_reverse',
    nameJa: 'キングリバース',
    descriptionJa: 'K(13)のカードを出すと場の順番が逆になる。',
    triggerRank: 13,
    triggerCount: 1,
    type: 'on_play',
  },

  // ============================================================
  // ランク発動型 (18個)
  // ============================================================
  ace_declare: {
    id: 'ace_declare',
    nameJa: 'A宣言',
    descriptionJa: 'A(1)を出すと、次のプレイヤーが出さなければならないランクを1つ指定できる。CPUは自動で最多ランクを指定する。',
    triggerRank: 1,
    triggerCount: 1,
    type: 'on_play',
  },
  two_reset: {
    id: 'two_reset',
    nameJa: '2リセット',
    descriptionJa: '2のカードを出すと場が流れ、すべての縛り(数縛り・色縛り)がリセットされる。',
    triggerRank: 2,
    triggerCount: 1,
    type: 'field_clear',
  },
  three_tax: {
    id: 'three_tax',
    nameJa: '3の税金',
    descriptionJa: '3のカードを出すと、他の全プレイヤーが手札から1枚ずつ捨てなければならない。',
    triggerRank: 3,
    triggerCount: 1,
    type: 'on_play',
  },
  six_peek: {
    id: 'six_peek',
    nameJa: '6透視',
    descriptionJa: '6のカードを出すと、次のプレイヤーの手札枚数と最強カードのランクが表示される。',
    triggerRank: 6,
    triggerCount: 1,
    type: 'on_play',
  },
  nine_barrier: {
    id: 'nine_barrier',
    nameJa: '9バリア',
    descriptionJa: '9のカードを出すと、次の1ターンは自分がパスさせられる効果を無効化する。',
    triggerRank: 9,
    triggerCount: 1,
    type: 'on_play',
  },
  jack_steal: {
    id: 'jack_steal',
    nameJa: 'J泥棒',
    descriptionJa: 'J(11)を出すと、次のプレイヤーの手札からランダムに1枚奪い自分の手札に加える。',
    triggerRank: 11,
    triggerCount: 1,
    type: 'on_play',
  },
  two_destroy: {
    id: 'two_destroy',
    nameJa: '2破壊',
    descriptionJa: '2のカードを出すと、場に出されているカードをすべてゲームから除外する。',
    triggerRank: 2,
    triggerCount: 1,
    type: 'on_play',
  },
  three_gift: {
    id: 'three_gift',
    nameJa: '3贈与',
    descriptionJa: '3のカードを出すと、自分の最弱カード1枚を次のプレイヤーに渡す。',
    triggerRank: 3,
    triggerCount: 1,
    type: 'on_play',
  },
  six_freeze: {
    id: 'six_freeze',
    nameJa: '6凍結',
    descriptionJa: '6のカードを出すと、次のプレイヤーは1ターン休みになる。',
    triggerRank: 6,
    triggerCount: 1,
    type: 'on_play',
  },
  ace_monopoly: {
    id: 'ace_monopoly',
    nameJa: 'Aモノポリー',
    descriptionJa: 'A(1)を出すと、場が流れる。強力なリセット効果。',
    triggerRank: 1,
    triggerCount: 1,
    type: 'field_clear',
  },
  nine_mirror: {
    id: 'nine_mirror',
    nameJa: '9ミラー',
    descriptionJa: '9のカードを出すと、前の人が出したカードと同じ枚数のカードを追加で出せる。',
    triggerRank: 9,
    triggerCount: 1,
    type: 'on_play',
  },
  two_double: {
    id: 'two_double',
    nameJa: '2ダブル',
    descriptionJa: '2のカードを出すと、次に出されるカードのルール効果が2倍になる。',
    triggerRank: 2,
    triggerCount: 1,
    type: 'on_play',
  },
  three_shield: {
    id: 'three_shield',
    nameJa: '3シールド',
    descriptionJa: '3のカードを出すと、次の1回の攻撃的なルール効果(泥棒、ボンバー等)を無効化する。',
    triggerRank: 3,
    triggerCount: 1,
    type: 'on_play',
  },
  six_shuffle: {
    id: 'six_shuffle',
    nameJa: '6シャッフル',
    descriptionJa: '6のカードを2枚出すと、全プレイヤーの手札をまとめてシャッフルし再配布する。',
    triggerRank: 6,
    triggerCount: 2,
    type: 'on_play',
  },
  jack_reverse_rank: {
    id: 'jack_reverse_rank',
    nameJa: 'J逆転',
    descriptionJa: 'J(11)を出すと、場が流れるまでカードの強弱が一時的に逆転する(革命と同様の効果)。',
    triggerRank: 11,
    triggerCount: 1,
    type: 'on_play',
  },
  ace_all_pass: {
    id: 'ace_all_pass',
    nameJa: 'A全流し',
    descriptionJa: 'A(1)を2枚以上出すと、全員が強制パスとなり場が流れる。',
    triggerRank: 1,
    triggerCount: 2,
    type: 'field_clear',
  },
  two_swap: {
    id: 'two_swap',
    nameJa: '2スワップ',
    descriptionJa: '2のカードを出すと、次のプレイヤーと手札を1枚ずつ交換する(自動で最弱同士を交換)。',
    triggerRank: 2,
    triggerCount: 1,
    type: 'on_play',
  },
  nine_copy: {
    id: 'nine_copy',
    nameJa: '9コピー',
    descriptionJa: '9のカードを出すと、直前に発動したルール効果をもう一度発動する。',
    triggerRank: 9,
    triggerCount: 1,
    type: 'on_play',
  },

  // ============================================================
  // スート効果型 (8個)
  // ============================================================
  spade_boost: {
    id: 'spade_boost',
    nameJa: 'スペードブースト',
    descriptionJa: 'スペードのカードを出すと、次の人のターンをスキップする追加効果がつく。',
    triggerRank: null,
    triggerCount: null,
    type: 'on_play',
  },
  heart_heal: {
    id: 'heart_heal',
    nameJa: 'ハート回復',
    descriptionJa: 'ハートのカードを出すと、捨て札からランダムに1枚手札に回収できる。',
    triggerRank: null,
    triggerCount: null,
    type: 'on_play',
  },
  diamond_draw: {
    id: 'diamond_draw',
    nameJa: 'ダイヤドロー',
    descriptionJa: 'ダイヤのカードを出すと、次のプレイヤーに自分の最弱カードを1枚押し付ける。',
    triggerRank: null,
    triggerCount: null,
    type: 'on_play',
  },
  club_crush: {
    id: 'club_crush',
    nameJa: 'クラブクラッシュ',
    descriptionJa: 'クラブのカードを3枚以上出すと場が流れる。',
    triggerRank: null,
    triggerCount: 3,
    type: 'field_clear',
  },
  spade_chain: {
    id: 'spade_chain',
    nameJa: 'スペード連鎖',
    descriptionJa: 'スペードを2回連続で出すと、もう1ターン追加で行動できる。',
    triggerRank: null,
    triggerCount: null,
    type: 'on_play',
  },
  heart_protect: {
    id: 'heart_protect',
    nameJa: 'ハートプロテクト',
    descriptionJa: 'ハートのカードが手札にある限り、都落ちの効果を受けない。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  diamond_bonus: {
    id: 'diamond_bonus',
    nameJa: 'ダイヤボーナス',
    descriptionJa: '最後にダイヤのカードであがると、そのラウンドの得点が2倍になる。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  club_penalty: {
    id: 'club_penalty',
    nameJa: 'クラブペナルティ',
    descriptionJa: 'クラブのカードを最後まで手札に残してしまうと、-5点のペナルティ。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },

  // ============================================================
  // コンボ効果型 (8個)
  // ============================================================
  double_pair_flush: {
    id: 'double_pair_flush',
    nameJa: 'ダブルペア流し',
    descriptionJa: 'ペア(2枚組)を出した時、手札にもう1組同じランクのペアがあれば場を流せる。',
    triggerRank: null,
    triggerCount: null,
    type: 'field_clear',
  },
  triple_power: {
    id: 'triple_power',
    nameJa: 'トリプルパワー',
    descriptionJa: '3枚出しの場合、そのカードに紐づくすべての追加ルール効果が発動する。',
    triggerRank: null,
    triggerCount: 3,
    type: 'on_play',
  },
  sequence_bonus: {
    id: 'sequence_bonus',
    nameJa: '階段ボーナス',
    descriptionJa: '階段(3枚以上の連番)を出すと場が流れ、もう一度自分のターンになる。',
    triggerRank: null,
    triggerCount: null,
    type: 'field_clear',
  },
  full_house: {
    id: 'full_house',
    nameJa: 'フルハウス',
    descriptionJa: '3枚+2枚の組み合わせで出すと場が流れ、他の全プレイヤーが1枚ずつ捨てる。',
    triggerRank: null,
    triggerCount: 5,
    type: 'field_clear',
  },
  quad_destroy: {
    id: 'quad_destroy',
    nameJa: '4枚大掃除',
    descriptionJa: '4枚出し(革命)の時、全プレイヤーの手札から最弱カードを1枚ずつ除外する。',
    triggerRank: null,
    triggerCount: 4,
    type: 'on_play',
  },
  pair_swap: {
    id: 'pair_swap',
    nameJa: 'ペア交換',
    descriptionJa: 'ペアを出すと、次のプレイヤーと手札を1枚ずつ自動交換する。',
    triggerRank: null,
    triggerCount: 2,
    type: 'on_play',
  },
  sequence_steal: {
    id: 'sequence_steal',
    nameJa: '階段泥棒',
    descriptionJa: '階段を出すと、各相手から手札をランダムに1枚ずつ奪う。',
    triggerRank: null,
    triggerCount: null,
    type: 'on_play',
  },
  same_suit_triple: {
    id: 'same_suit_triple',
    nameJa: '同色トリプル',
    descriptionJa: '同じスートのカードを3枚出すと、次のプレイヤーを2ターン休みにする。',
    triggerRank: null,
    triggerCount: 3,
    type: 'on_play',
  },

  // ============================================================
  // パッシブ型 (7個)
  // ============================================================
  speed_round: {
    id: 'speed_round',
    nameJa: 'スピードラウンド',
    descriptionJa: 'ターンの制限時間が半分(15秒)になる。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  joker_nerf: {
    id: 'joker_nerf',
    nameJa: 'ジョーカー弱体',
    descriptionJa: 'ジョーカーを最後の1枚として出してあがることができなくなる。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  transparency: {
    id: 'transparency',
    nameJa: '情報公開',
    descriptionJa: '各プレイヤーの手札に残っているスートの内訳が全員に表示される。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  lucky_start: {
    id: 'lucky_start',
    nameJa: 'ラッキースタート',
    descriptionJa: '各ラウンド開始時、全プレイヤーが捨て札からランダムに1枚追加で手札に加える。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  escalation: {
    id: 'escalation',
    nameJa: 'エスカレーション',
    descriptionJa: 'ラウンドが進むごとに、最低出し枚数が1ずつ増加する(2回戦目は2枚以上、3回戦目は3枚以上)。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  mercy_rule: {
    id: 'mercy_rule',
    nameJa: '慈悲ルール',
    descriptionJa: '前回の大貧民は、次のラウンド開始時に捨て札から2枚追加で手札に加える。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  sudden_death: {
    id: 'sudden_death',
    nameJa: 'サドンデス',
    descriptionJa: '残りプレイヤーが2人になったら、パスした方が即座に大貧民になる。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },

  // ============================================================
  // 場効果型 (5個)
  // ============================================================
  field_tax: {
    id: 'field_tax',
    nameJa: '場の税金',
    descriptionJa: '場が流れるたびに、全プレイヤーが手札から最弱カードを1枚ずつ自動で捨てる。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  lucky_seven: {
    id: 'lucky_seven',
    nameJa: 'ラッキー7',
    descriptionJa: '7のカードで場が流れた場合、次のターンは好きなカードを1枚だけ自由に出せる(強さ無視)。',
    triggerRank: 7,
    triggerCount: 1,
    type: 'on_play',
  },
  chain_bonus: {
    id: 'chain_bonus',
    nameJa: '連鎖ボーナス',
    descriptionJa: '3回連続でパスせずにカードを出せたら、+3点のボーナス。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  poison_field: {
    id: 'poison_field',
    nameJa: '毒の場',
    descriptionJa: '場にカードが5枚以上溜まると自動的に場が流れる。',
    triggerRank: null,
    triggerCount: 5,
    type: 'field_clear',
  },
  echo_field: {
    id: 'echo_field',
    nameJa: 'エコーフィールド',
    descriptionJa: '場が流れた時、最後に出されたカードのランクと同じカードを持っている人は+2点。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },

  // ============================================================
  // スコア型 (5個)
  // ============================================================
  speed_bonus: {
    id: 'speed_bonus',
    nameJa: '速攻ボーナス',
    descriptionJa: '最初にあがったプレイヤーに追加で+10点のボーナス。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  revolution_bonus: {
    id: 'revolution_bonus',
    nameJa: '革命ボーナス',
    descriptionJa: '革命を成功させたプレイヤーに+5点のボーナス。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  pass_penalty: {
    id: 'pass_penalty',
    nameJa: 'パスペナルティ',
    descriptionJa: 'パスするたびに-1点のペナルティを受ける。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  empty_hand_bonus: {
    id: 'empty_hand_bonus',
    nameJa: '完全消化ボーナス',
    descriptionJa: '最後のカードをペア以上で出してあがると+5点のボーナス。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
  diversity_bonus: {
    id: 'diversity_bonus',
    nameJa: '多様性ボーナス',
    descriptionJa: '4スート(スペード・ハート・ダイヤ・クラブ)すべてを使ってあがると+5点。',
    triggerRank: null,
    triggerCount: null,
    type: 'passive',
  },
};

export const ALL_RULE_IDS: AdditionalRuleId[] = Object.keys(ADDITIONAL_RULES) as AdditionalRuleId[];
